version: "3.9"
services:
  production-ready-node-api:
    image: postgres:17
    restart: always
    container_name: production-ready-node-api
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
