export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  HOST_NAME: process.env.HOST_NAME!,
  STORAGE_BUCKET_NAME: process.env.STORAGE_BUCKET_NAME!,
  NODE_ENV: process.env.NODE_ENV!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_PRICE_ID: process.env.STRIPE_PRICE_ID!,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL!,
};
